# Comiks config file

# Threshold to highlight authors with a name/email similiar to the given
# username in CLI output (should be between 0 and 1).
# Set to 1 for exact match.
score_threshold = 0.4

# Providers configuration
[provider]

[provider.GitHub]
enabled = true
# Authenticated requests to Github API get a higher rate limit
# The username to authenticate is your account username
username = ""
# You need to create an access token
# https://github.com/settings/tokens
access_token = ""

[provider.GitLab]
enabled = false
# GitLab provider needs an access token with read_api access
# https://gitlab.com/-/profile/personal_access_tokens
access_token = ""

[provider.Bitbucket]
enabled = false
# The username to authenticate is your account username
# https://bitbucket.org/account/settings/
username = ""
# You needs an app password
# https://bitbucket.org/account/settings/app-passwords/
# Give at least repositories read access permission
app_password = ""
