# Comiks config file

# Threshold to highlight authors with a name/email similiar to the given
# username in CLI output (should be between 0 and 1).
# Set to 1 for exact match.
score_threshold = 0.4

# Providers configuration
[provider]

[provider.GitHub]
enabled = true
# Authenticated requests to Github API get a higher rate limit
username = ""
access_token = ""

[provider.GitLab]
enabled = false
# GitLab provider need an access token with read_api access
access_token = ""
